name: Docker Image CI for gen-assoc m-TDT

on:
  push:
    branches: [ maindev ]
  pull_request:
    branches: [ maindev ]

jobs:

  build:

    runs-on: node:17-bullseye

    steps:
    - uses: actions/checkout@v2
    - name: Gen Assoc m-tdt image
      run: docker build . -t  mtdt:devbuild
