name: NodeJS with Webpack

on:
  push:
    branches: [ maindev ]
  pull_request:
    branches: [ maindev ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x,17.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        cd apps
        npm install
        npm run compile
